const SERVICES = {
  'individual-therapy': {
    id: 'individual-therapy',
    title: 'Individual Therapy',
    subtitle: 'One-on-one sessions tailored to your unique needs and goals.',
    icon: `<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#E57373" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>`,
    iconBg: '#FFF1F1',
    duration: '50 minutes',
    price: '$190',
    format: 'In-person & Online',
    about: 'Individual therapy provides a safe, confidential space where you can explore your thoughts, feelings, and behaviors with a trained professional. This personalized approach allows us to focus entirely on your unique experiences and goals, creating a treatment plan that\'s specifically designed for you.',
    tags: ['Anxiety & Depression', 'Trauma Recovery', 'Life Transitions', 'Self-Esteem Building'],
    benefits: [
      'Personalized treatment approach', 'Confidential and safe environment',
      'Flexible scheduling options', 'Evidence-based therapeutic techniques',
      'Goal-oriented sessions', 'Long-term emotional growth',
    ],
    whoHelps: [
      'Individuals experiencing anxiety or depression',
      'Those navigating major life transitions',
      'People seeking personal growth and self-awareness',
      'Anyone dealing with relationship challenges',
      'Individuals recovering from trauma',
    ],
    process: [
      'Initial assessment and goal setting',
      'Development of personalized treatment plan',
      'Regular therapy sessions with progress monitoring',
      'Skill building and coping strategy development',
      'Ongoing evaluation and plan adjustments',
    ],
    whatToExpect: "In your first session, we'll discuss what brings you to therapy and establish your goals. Each session builds on the previous one, with homework or exercises that support your progress between appointments.",
    otherServices: ['couples-therapy', 'cbt', 'mindfulness'],
  },

  'couples-therapy': {
    id: 'couples-therapy',
    title: 'Couples Therapy',
    subtitle: 'Strengthen your relationship through improved communication and understanding.',
    icon: `<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#7986CB" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>`,
    iconBg: '#F3F0FF',
    duration: '50 minutes',
    price: '$190',
    format: 'In-person & Online',
    about: 'Couples therapy helps partners improve their relationship by developing better communication skills, resolving conflicts, and building deeper emotional connection. Whether you\'re newlyweds or have been together for decades, couples therapy can strengthen your bond.',
    tags: ['Communication Skills', 'Conflict Resolution', 'Intimacy Issues', 'Pre-marital Counseling'],
    benefits: [
      'Improved communication patterns', 'Enhanced conflict resolution skills',
      'Deeper emotional intimacy', 'Better understanding of each other\'s needs',
      'Stronger relationship foundation', 'Prevention of future relationship issues',
    ],
    whoHelps: [
      'Couples experiencing communication difficulties',
      'Partners dealing with trust issues',
      'Couples preparing for marriage',
      'Those navigating major life changes together',
      'Partners wanting to strengthen their relationship',
    ],
    process: [
      'Joint assessment of relationship dynamics',
      'Identification of communication patterns',
      'Learning new communication tools and techniques',
      'Practice exercises both in session and at home',
      'Regular progress reviews and goal adjustments',
    ],
    whatToExpect: 'Sessions involve both partners working together with the therapist to identify patterns, learn new skills, and practice healthier ways of relating to each other.',
    otherServices: ['individual-therapy', 'cbt', 'mindfulness'],
  },

  'cbt': {
    id: 'cbt',
    title: 'Cognitive Behavioral Therapy',
    subtitle: 'Evidence-based approach to changing negative thought patterns and behaviors.',
    icon: `<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#AB47BC" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 8v4l3 3"/></svg>`,
    iconBg: '#F9F0FF',
    duration: '50 minutes',
    price: '$190',
    format: 'In-person & Online',
    about: 'Cognitive Behavioral Therapy (CBT) is a highly effective, evidence-based treatment that focuses on identifying and changing negative thought patterns and behaviors. CBT is goal-oriented and typically shorter-term than other therapy approaches.',
    tags: ['Thought Restructuring', 'Behavioral Activation', 'Exposure Therapy', 'Skill Building'],
    benefits: [
      'Evidence-based treatment approach', 'Faster results with structured sessions',
      'Practical tools for daily life', 'Improved emotional regulation',
      'Better problem-solving skills', 'Long-lasting positive changes',
    ],
    whoHelps: [
      'Individuals with anxiety disorders',
      'People experiencing depression',
      'Those with obsessive-compulsive tendencies',
      'Individuals seeking practical coping strategies',
      'Anyone wanting to change specific behaviors',
    ],
    process: [
      'Assessment of current thought and behavior patterns',
      'Identification of negative thinking cycles',
      'Learning cognitive restructuring techniques',
      'Behavioral experiments and homework assignments',
      'Skill practice and reinforcement',
    ],
    whatToExpect: "CBT sessions are structured and goal-focused. You'll learn specific techniques to identify and challenge negative thoughts, and practice new behaviors both in session and through homework assignments.",
    otherServices: ['individual-therapy', 'couples-therapy', 'mindfulness'],
  },

  'mindfulness': {
    id: 'mindfulness',
    title: 'Mindfulness-Based Therapy',
    subtitle: 'Integrate mindfulness practices to reduce stress and increase self-awareness.',
    icon: `<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#F59E0B" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>`,
    iconBg: '#FFFBEB',
    duration: '50 minutes',
    price: '$190',
    format: 'In-person & Online',
    about: 'Mindfulness-Based Therapy combines traditional therapeutic approaches with mindfulness meditation practices. This integration helps you develop greater awareness of your thoughts, feelings, and bodily sensations, leading to improved emotional regulation and stress management.',
    tags: ['Meditation Techniques', 'Stress Reduction', 'Present Moment Awareness', 'Emotional Regulation'],
    benefits: [
      'Reduced stress and anxiety levels', 'Improved emotional regulation',
      'Greater self-awareness', 'Better focus and concentration',
      'Enhanced overall well-being', 'Tools for daily stress management',
    ],
    whoHelps: [
      'Individuals experiencing chronic stress',
      'Those seeking greater self-awareness',
      'People interested in meditation and mindfulness',
      'Individuals with anxiety or racing thoughts',
      'Anyone wanting to improve emotional balance',
    ],
    process: [
      'Introduction to mindfulness principles and practices',
      'Guided meditation and breathing exercises',
      'Integration of mindfulness into daily activities',
      'Development of personal mindfulness practice',
      'Application of mindful awareness to life challenges',
    ],
    whatToExpect: 'Sessions include guided mindfulness exercises, discussion of your practice, and exploration of how mindfulness can be applied to your specific challenges and goals.',
    otherServices: ['individual-therapy', 'couples-therapy', 'cbt'],
  },

  'trauma': {
    id: 'trauma',
    title: 'Trauma-Informed Care',
    subtitle: 'Specialized treatment for trauma survivors using evidence-based approaches.',
    icon: `<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#397DFF" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
    iconBg: '#EFF6FF',
    duration: '50 minutes',
    price: '$190',
    format: 'In-person & Online',
    about: 'Trauma-Informed Care recognizes the widespread impact of trauma and prioritizes safety, trustworthiness, and healing. This approach uses specialized techniques like EMDR and somatic therapies to help process traumatic experiences safely.',
    tags: ['EMDR Therapy', 'Somatic Approaches', 'Safety Planning', 'Resilience Building'],
    benefits: [
      'Safe processing of traumatic memories', 'Reduction in trauma-related symptoms',
      'Improved sense of safety and control', 'Enhanced emotional regulation',
      'Stronger resilience and coping skills', 'Restored sense of empowerment',
    ],
    whoHelps: [
      'Survivors of childhood trauma',
      'Individuals with PTSD symptoms',
      'Those who have experienced recent trauma',
      'People with complex trauma histories',
      'Anyone seeking trauma-informed support',
    ],
    process: [
      'Trauma assessment and safety planning',
      'Stabilization and resource building',
      'Gradual trauma processing using specialized techniques',
      'Integration and consolidation of healing',
      'Relapse prevention and ongoing support',
    ],
    whatToExpect: 'Treatment begins with establishing safety and building coping resources before gradually processing traumatic memories using specialized, evidence-based techniques at your own pace.',
    otherServices: ['individual-therapy', 'couples-therapy', 'cbt'],
  },

  'brief-solution': {
    id: 'brief-solution',
    title: 'Brief Solution-Focused Therapy',
    subtitle: 'Goal-oriented therapy focused on solutions and achieving specific outcomes.',
    icon: `<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#14B8A6" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>`,
    iconBg: '#F0FDFA',
    duration: '50 minutes',
    price: '$190',
    format: 'In-person & Online',
    about: 'Brief Solution-Focused Therapy (BSFT) is a goal-oriented approach that focuses on solutions rather than problems. This efficient therapy model helps you identify your strengths and resources to create positive changes in a shorter timeframe.',
    tags: ['Goal Setting', 'Solution Finding', 'Strength Building', 'Future Planning'],
    benefits: [
      'Faster achievement of therapeutic goals', 'Focus on strengths and resources',
      'Practical, actionable solutions', 'Increased self-confidence',
      'Cost-effective treatment option', 'Applicable to various life challenges',
    ],
    whoHelps: [
      'Individuals with specific, well-defined goals',
      'Those seeking shorter-term therapy',
      'People facing particular life challenges',
      'Individuals who prefer action-oriented approaches',
      'Anyone wanting to focus on solutions rather than problems',
    ],
    process: [
      'Clear goal identification and prioritization',
      'Assessment of existing strengths and resources',
      'Development of solution-focused strategies',
      'Implementation of action steps',
      'Regular progress monitoring and adjustments',
    ],
    whatToExpect: "Sessions are highly focused on your goals and the steps needed to achieve them. We'll identify what's already working in your life and build on those strengths to create sustainable change.",
    otherServices: ['individual-therapy', 'couples-therapy', 'cbt'],
  },
};
